### ISSUE TITLE
move project over to adtools

### ISSUE THREAD

**Issue by jens-maus** [adtools/amigaos-cross-toolchain#55]
I would like to request/ask you if you could consider moving your amigaos-cross-toolchain project over to the adtools project (https://github.com/adtools). IMHO this would be a better place for this project. In addition, it would be great if you could also move over your sub projects (gcc-2.95.3, etc.) to adtools. This would be very much welcome!

**Comment by cahirwpz** [comment]
@jens-maus After a long period of inactivity I came to conclusion that I'm not anymore interested in developing this toolchain. I'm in favour of handling the repository over to adtools. Are you still interested?

**Comment by jens-maus** [comment]
@cahirwpz I am not such much active in the Amiga field myself anymore. However, I still feel that this projects might still have some interested users/developers and so it would be IMHO still be better suited within the "adtools" organization. So if you want to move it over to adtools, please do so because there more than just me are part of the organization.

**Comment by cahirwpz** [comment]
Done!
